# version: '3.2'

services:
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extensions:/var/www/FreshRSS/extensions
    ports:
      - 8080:80
    environment:
      TZ: Asia/Shanghai
      CRON_MIN: '3,33'

  rsshub:
    image: diygod/rsshub
    container_name: rsshub
    hostname: rsshub
    restart: unless-stopped
    ports:
      - 1200:1200
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
      PUPPETEER_WS_ENDPOINT: 'ws://browserless-chrome:3000'
      GITHUB_ACCESS_TOKEN: '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'
    depends_on:
      - redis
      - browserless-chrome
  
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://browserless-chrome:3000/?stealth=1&--disable-web-security=true
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - browserless-chrome

  browserless-chrome:
    # default hostname is the service name
    image: browserless/chrome
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

  n8n:
    # image: docker.n8n.io/n8nio/n8n
    build:
      context: .
      dockerfile: n8n_Dockerfile
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - GENERIC_TIMEZONE=Asia/Shanghai
      - TZ=Asia/Shanghai
    volumes:
      - n8n-data:/home/node/.n8n
      - /root/rss-everything/n8n-scripts:/home/scripts
      - /root/rss-everything/n8n-files:/home/files

volumes:
  freshrss-data:
  freshrss-extensions:
  changedetection-data:
  redis-data:
  n8n-data:

