version: '3.2'
services:
  n8n:
    # image: docker.n8n.io/n8nio/n8n
    build:
      context: .
      dockerfile: Dockerfile_n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - GENERIC_TIMEZONE=Asia/Shanghai
      - TZ=Asia/Shanghai
    volumes:
      - n8n_data:/home/node/.n8n
      - /root/rss-everything/n8n_docker/scripts:/home/scripts
      - /root/rss-everything/n8n_docker/files:/home/files

volumes:
  n8n_data:
