FROM docker.n8n.io/n8nio/n8n
# swith to root
USER root
RUN apk add --update python3 py3-pip
RUN python3 -m pip install --break-system-packages feedparser feedgenerator 
RUN python3 -m pip install --break-system-packages openai slack_sdk
RUN python3 -m pip install --break-system-packages bs4 requests selenium
# switch back to the original pod user
USER node
